from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, Literal, List
from datetime import datetime


# --- Chore & Ticket Schemas ---
class ChoreCreate(BaseModel):
    name: str
    description: Optional[str] = None
    difficulty_level: int  # 1-5
    chore_frequency: str  # "Weekly", "Daily"


class TicketUpdate(BaseModel):
    status: str  # "Completed", "Pending"


# --- Gemini Structured Output Schema ---
class GeneratedChore(BaseModel):
    """Schema for chores generated by Gemini AI - represents one instance for the week"""

    name: str = Field(
        description="Name of the chore (must match one from available chores list)"
    )
    description: str = Field(
        description="Detailed description of what needs to be done"
    )
    difficulty_level: int = Field(
        description="Difficulty level from 1 (easy) to 5 (hard)", ge=1, le=5
    )
    duration: int = Field(description="Estimated duration in minutes", ge=1)
    chore_frequency: Literal["Daily", "Weekly", "Monthly", "One-time"] = Field(
        description="How often this chore needs to be done"
    )
    chore_priority: int = Field(
        description="Priority level from 1 (low) to 3 (high)", ge=1, le=3
    )
    notes: Optional[str] = Field(
        default=None, description="Any additional notes or considerations"
    )
    assigned_user_id: str = Field(
        description="User ID who should be assigned this specific instance"
    )
    day_of_week: Optional[
        Literal[
            "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
        ]
    ] = Field(
        default=None,
        description="Day of the week for this instance (required for Daily chores, optional for others)",
    )
    reason: Optional[str] = Field(
        default=None, description="Reason for the assignment to this user"
    )
