from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, Literal, List
from datetime import datetime


# --- Chore & Ticket Schemas ---
class ChoreCreate(BaseModel):
    name: str
    description: Optional[str] = None
    difficulty_level: int  # 1-3
    duration: int  # in minutes
    chore_frequency: str  # "Weekly", "Daily"
    chore_priority: int  # 1-3 low medium high
    notes: Optional[str] = None
    icon: Optional[str] = None  # NEW


class TicketUpdate(BaseModel):
    status: str  # "Completed", "Pending"


class TicketDueDateUpdate(BaseModel):
    due_date: str  # ISO format date string


class TicketAssignmentUpdate(BaseModel):
    assigned_user_id: str  # UUID of new assignee


# --- Gemini Structured Output Schema ---
class GeneratedChore(BaseModel):
    """Schema for chores generated by Gemini AI - represents one instance for the week"""

    name: str = Field(description="Name of the chore")
    description: str = Field(
        description="""
        Detailed description of what needs to be done. 
        A clear and concise explanation of why the chore is required for the house.
        """
    )
    difficulty_level: int = Field(
        description="Difficulty level from 1 (easy) to 3 (hard)", ge=1, le=3
    )
    duration: int = Field(description="Estimated duration in minutes", ge=5, le=60)
    chore_frequency: Literal[
        "Daily", "Twice a week", "Weekly", "Once in two weeks", "Monthly"
    ] = Field(
        description="""
        How often this chore needs to be done. Daily means once a day. 
        Twice a week means twice a week. Weekly means once a week. 
        Once in two weeks means once every two weeks. Monthly means once a month.
        """
    )
    chore_priority: int = Field(
        ge=1,
        le=3,
        description="""
        Priority level from 1 (low) to 3 (high). 1 means the chore is not important and can be done later. 
        2 means the chore is important and should be done soon. 
        3 means the chore is very important and should be done immediately.
        """,
    )
    notes: Optional[str] = Field(
        default=None,
        description="""
        Justifying why the difficulty level, duration, chore frequency, chore priority, icon, and a concrete reason 
        for the creation are set the way they are.
        """,
    )
    icon: Optional[str] = Field(
        default=None,
        description="Emoji representing this chore. Use appropriate emojis that visually represent the chore.",
    )


# --- Response Schema for Tickets with Chore Details ---
class TicketWithChoreDetails(BaseModel):
    """Response schema for tickets joined with chore and user information"""

    # Ticket fields
    ticket_id: str
    due_date: datetime
    status: str

    # Chore fields
    chore_name: str
    difficulty_level: int
    duration: int

    # User fields
    assigned_user_name: str

    class Config:
        from_attributes = True
